/* automatically generated from xfwm4-tweaks-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tweaks_dialog_ui)
#endif
#ifdef __GNUC__
static const char tweaks_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tweaks_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kAdjustment\" id=\"adjustment1\"><property name=\"upper\">100</property"
  "><property name=\"value\">75</property><property name=\"step_increment\""
  ">1</property><property name=\"page_increment\">10</property></object><o"
  "bject class=\"GtkAdjustment\" id=\"adjustment2\"><property name=\"upper"
  "\">100</property><property name=\"value\">90</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"adjustment3\"><prope"
  "rty name=\"upper\">100</property><property name=\"value\">90</property>"
  "<property name=\"step_increment\">1</property><property name=\"page_inc"
  "rement\">10</property></object><object class=\"GtkAdjustment\" id=\"adj"
  "ustment4\"><property name=\"upper\">100</property><property name=\"valu"
  "e\">90</property><property name=\"step_increment\">1</property><propert"
  "y name=\"page_increment\">10</property></object><object class=\"GtkAdju"
  "stment\" id=\"adjustment5\"><property name=\"upper\">100</property><pro"
  "perty name=\"value\">90</property><property name=\"step_increment\">1</"
  "property><property name=\"page_increment\">10</property></object><objec"
  "t class=\"GtkAdjustment\" id=\"adjustment6\"><property name=\"upper\">1"
  "00</property><property name=\"value\">90</property><property name=\"ste"
  "p_increment\">1</property><property name=\"page_increment\">10</propert"
  "y></object><object class=\"GtkImage\" id=\"image1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"icon_name\">window-close</property></object><object class"
  "=\"GtkImage\" id=\"image2\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"icon_name\""
  ">help-browser</property></object><object class=\"XfceTitledDialog\" id="
  "\"main-dialog\"><property name=\"can_focus\">False</property><property "
  "name=\"title\" translatable=\"yes\">Window Manager Tweaks</property><pr"
  "operty name=\"window_position\">center-on-parent</property><property na"
  "me=\"default_height\">480</property><property name=\"icon_name\">org.xf"
  "ce.xfwm4-tweaks</property><property name=\"type_hint\">dialog</property"
  "><property name=\"subtitle\" translatable=\"yes\">Fine-tune window beha"
  "viour and effects</property><child internal-child=\"vbox\"><object clas"
  "s=\"GtkBox\" id=\"main-vbox\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"orientat"
  "ion\">vertical</property><child internal-child=\"action_area\"><object "
  "class=\"GtkButtonBox\" id=\"dialog-action_area1\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"layout_style\">end</property><child><object class=\"GtkButt"
  "on\" id=\"button2\"><property name=\"label\" translatable=\"yes\">_Help"
  "</property><property name=\"use_action_appearance\">False</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">True</property><propert"
  "y name=\"image\">image2</property><property name=\"use_underline\">True"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">0</"
  "property><property name=\"secondary\">True</property></packing></child>"
  "<child><object class=\"GtkButton\" id=\"button1\"><property name=\"labe"
  "l\" translatable=\"yes\">_Close</property><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">True</property><property name=\"image\">image1</property><prope"
  "rty name=\"use_underline\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">1</property></packing></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"pack_type\">end</property><property nam"
  "e=\"position\">0</property></packing></child><child><object class=\"Gtk"
  "Notebook\" id=\"plug-child\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"border_wid"
  "th\">6</property><child><object class=\"GtkBox\" id=\"vbox1\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"orientation\">vertical</property><property name"
  "=\"border_width\">12</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkCheckButton\" id=\"cycle_minimum_check\"><prop"
  "erty name=\"label\" translatable=\"yes\">S_kip windows that have \"skip"
  " pager\"\nor \"skip taskbar\" properties set</property><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkCheckButton\" id=\"cycle_minimized_chec"
  "k\"><property name=\"label\" translatable=\"no\">Cycle _through minimiz"
  "ed windows in most recently used order</property><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">1</property></packing></chil"
  "d><child><object class=\"GtkCheckButton\" id=\"cycle_hidden_check\"><pr"
  "operty name=\"label\" translatable=\"yes\">_Include hidden (i.e. iconif"
  "ied) windows</property><property name=\"use_action_appearance\">False</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">False</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"d"
  "raw_indicator\">True</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">False</property><property n"
  "ame=\"position\">2</property></packing></child><child><object class=\"G"
  "tkCheckButton\" id=\"cycle_workspaces_check\"><property name=\"label\" "
  "translatable=\"yes\">Cycle _through windows on all workspaces</property"
  "><property name=\"use_action_appearance\">False</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">3</pr"
  "operty></packing></child><child><object class=\"GtkCheckButton\" id=\"c"
  "ycle_draw_frame\"><property name=\"label\" translatable=\"yes\">_Draw f"
  "rame around selected window while cycling</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">4</property></packing></ch"
  "ild><child><object class=\"GtkCheckButton\" id=\"cycle_raise\"><propert"
  "y name=\"label\" translatable=\"yes\">_Raise windows while cycling</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "5</property></packing></child><child><object class=\"GtkCheckButton\" i"
  "d=\"cycle_tabwin_mode\"><property name=\"label\" translatable=\"yes\">C"
  "ycle through windows in a _list</property><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">False</property><property name=\"use_underline\">True</property"
  "><property name=\"draw_indicator\">True</property></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">False</p"
  "roperty><property name=\"position\">6</property></packing></child></obj"
  "ect></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">C_ycling"
  "</property><property name=\"use_underline\">True</property></object><pa"
  "cking><property name=\"tab_fill\">False</property></packing></child><ch"
  "ild><object class=\"GtkBox\" id=\"vbox3\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"orientation\">vertical</property><property name=\"border_width\">12"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkCheckButton\" id=\"prevent_focus_stealing_check\"><property name=\""
  "label\" translatable=\"yes\">Activate foc_us stealing prevention</prope"
  "rty><property name=\"use_action_appearance\">False</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">False</property><property name"
  "=\"use_underline\">True</property><property name=\"draw_indicator\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkCheckButton\" id="
  "\"focus_hint_check\"><property name=\"label\" translatable=\"yes\">Hono"
  "r _standard ICCCM focus hint</property><property name=\"use_action_appe"
  "arance\">False</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">False</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"draw_indicator\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">1</property></packing></child><child><"
  "object class=\"GtkBox\" id=\"prevent_focus_stealing_box\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"orientation\">vertical</property><property name=\"s"
  "pacing\">6</property><child><object class=\"GtkLabel\" id=\"label11\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"xalign\">0</property><property name=\"l"
  "abel\" translatable=\"yes\">When a window raises itself:</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkAlignment\" id=\"alignment2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"bottom_padding\">6</property><property name="
  "\"left_padding\">12</property><child><object class=\"GtkBox\" id=\"vbox"
  "14\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"orientation\">vertical</property>"
  "<property name=\"border_width\">6</property><property name=\"spacing\">"
  "6</property><child><object class=\"GtkRadioButton\" id=\"activate_actio"
  "n_bring_option\"><property name=\"label\" translatable=\"yes\">_Bring w"
  "indow on current workspace</property><property name=\"use_action_appear"
  "ance\">False</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"active\">True</property><property name=\"draw_indicator\">"
  "True</property></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkRadioButton\" id"
  "=\"activate_action_switch_option\"><property name=\"label\" translatabl"
  "e=\"yes\">Switch to win_dow\'s workspace</property><property name=\"use"
  "_action_appearance\">False</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">False</property><property name=\"use_underline\">True<"
  "/property><property name=\"active\">True</property><property name=\"dra"
  "w_indicator\">True</property><property name=\"group\">activate_action_b"
  "ring_option</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkRadioButt"
  "on\" id=\"activate_action_none_option\"><property name=\"label\" transl"
  "atable=\"yes\">Do _nothing</property><property name=\"use_action_appear"
  "ance\">False</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"active\">True</property><property name=\"draw_indicator\">"
  "True</property><property name=\"group\">activate_action_bring_option</p"
  "roperty></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">2</prope"
  "rty></packing></child></object></child></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">2</property></packing></child></"
  "object><packing><property name=\"position\">1</property></packing></chi"
  "ld><child type=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label\" translatable=\"yes\">_Focus</property"
  "><property name=\"use_underline\">True</property></object><packing><pro"
  "perty name=\"position\">1</property><property name=\"tab_fill\">False</"
  "property></packing></child><child><object class=\"GtkBox\" id=\"vbox4\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"orientation\">vertical</property><pro"
  "perty name=\"border_width\">12</property><property name=\"spacing\">6</"
  "property><child><object class=\"GtkBox\" id=\"hbox1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">horizontal</property><property name=\"spa"
  "cing\">12</property><child><object class=\"GtkLabel\" id=\"label7\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"xalign\">0</property><property name=\"lab"
  "el\" translatable=\"yes\">Key used to _grab and move windows:</property"
  "><property name=\"use_underline\">True</property><property name=\"mnemo"
  "nic_widget\">easy_click_combo_box</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkComboBox\" id=\"easy_click_combo_box\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">1</property></p"
  "acking></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"raise_with_any_button_check\"><property name=\"label\" translatabl"
  "e=\"yes\">_Raise windows when any mouse button is pressed</property><pr"
  "operty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"borde"
  "rless_maximize_check\"><property name=\"label\" translatable=\"yes\">Hi"
  "de frame of windows when ma_ximized</property><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">False</property><property name=\"use_underline\">True</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">2</property></packing></child><"
  "child><object class=\"GtkCheckButton\" id=\"titleless_maximize_check\">"
  "<property name=\"label\" translatable=\"yes\">Hide title of windows whe"
  "n maximized</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">3</property></packing></child><child><obje"
  "ct class=\"GtkCheckButton\" id=\"tile_on_move_check\"><property name=\""
  "label\" translatable=\"yes\">Automatically _tile windows when moving to"
  "ward the screen edge</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">4</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"snap_resist_check\"><property name=\"label"
  "\" translatable=\"yes\">Use _edge resistance instead of window snapping"
  "</property><property name=\"use_action_appearance\">False</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">False</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"draw_indicato"
  "r\">True</property></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">False</property><property name=\"positi"
  "on\">5</property></packing></child><child><object class=\"GtkCheckButto"
  "n\" id=\"mousewheel_rollup\"><property name=\"label\" translatable=\"ye"
  "s\">Use mouse wheel on title bar to ro_ll up the window</property><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"use_un"
  "derline\">True</property><property name=\"draw_indicator\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">6</property"
  "></packing></child><child><object class=\"GtkCheckButton\" id=\"urgent_"
  "blink\"><property name=\"label\" translatable=\"yes\">Notify of _urgenc"
  "y by making window\'s decoration blink</property><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">7</property></packing></chil"
  "d><child><object class=\"GtkCheckButton\" id=\"repeat_urgent_blink\"><p"
  "roperty name=\"label\" translatable=\"yes\">Keep urgent windows _blinki"
  "ng repeatedly</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">8</property></packing></child></object><packing><prop"
  "erty name=\"position\">2</property></packing></child><child type=\"tab\""
  "><object class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">_Accessibility</property><property nam"
  "e=\"use_underline\">True</property></object><packing><property name=\"p"
  "osition\">2</property><property name=\"tab_fill\">False</property></pac"
  "king></child><child><object class=\"GtkBox\" id=\"vbox5\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"orientation\">vertical</property><property name=\"b"
  "order_width\">12</property><property name=\"spacing\">6</property><chil"
  "d><object class=\"GtkCheckButton\" id=\"scroll_workspaces_check\"><prop"
  "erty name=\"label\" translatable=\"yes\">Use the _mouse wheel on the de"
  "sktop to switch workspaces</property><property name=\"use_action_appear"
  "ance\">False</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"toggle_workspaces_check\"><property "
  "name=\"label\" translatable=\"yes\">_Remember and recall previous works"
  "pace\nwhen switching via keyboard shortcuts</property><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">1</property></packing></"
  "child><child><object class=\"GtkCheckButton\" id=\"wrap_layout_check\">"
  "<property name=\"label\" translatable=\"yes\">Wrap workspaces depending"
  " on the actual desktop _layout</property><property name=\"use_action_ap"
  "pearance\">False</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">False</property><property name=\"use_underline\">True</property>"
  "<property name=\"draw_indicator\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">2</property></packing></child><child"
  "><object class=\"GtkCheckButton\" id=\"wrap_cycle_check\"><property nam"
  "e=\"label\" translatable=\"yes\">Wrap workspaces when _the first or the"
  " last workspace is reached</property><property name=\"use_action_appear"
  "ance\">False</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">3</property></packing></child></object><"
  "packing><property name=\"position\">3</property></packing></child><chil"
  "d type=\"tab\"><object class=\"GtkLabel\" id=\"label4\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">_Workspaces</property><p"
  "roperty name=\"use_underline\">True</property></object><packing><proper"
  "ty name=\"position\">3</property><property name=\"tab_fill\">False</pro"
  "perty></packing></child><child><object class=\"GtkBox\" id=\"vbox6\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"border_width\">12</property><property name=\"spacing\">6</pro"
  "perty><child><object class=\"GtkLabel\" id=\"label8\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">_Minimum size of windows to trigger smart placement:</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"mn"
  "emonic_widget\">placement_ratio_scale</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkAlignment\" id=\"alignment4\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"bottom_padding\">6</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkBox\" id=\"hbox2\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"orientation\">horizontal</property><property name="
  "\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"label9\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\" comments"
  "=\"Smart placement size\">&lt;i&gt;Small&lt;/i&gt;</property><property "
  "name=\"use_markup\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkScale\" id=\"placement_ratio_scale\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"orientation\">horizontal</property><property name=\"adjustment\">ad"
  "justment1</property><property name=\"restrict_to_fill_level\">False</pr"
  "operty><property name=\"draw_value\">False</property></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></child><chi"
  "ld><object class=\"GtkLabel\" id=\"label10\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\" comments=\"Smart placement size\">&"
  "lt;i&gt;Large&lt;/i&gt;</property><property name=\"use_markup\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">2</prop"
  "erty></packing></child></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkBox\" id=\"default_placement_box\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">6</p"
  "roperty><child><object class=\"GtkLabel\" id=\"label27\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"xalign\">0</property><property name=\"label\" transl"
  "atable=\"yes\">By default, place windows:</property></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkAlignment\" id=\"alignment10\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"bottom_padding\">6</property><property name=\"left_paddin"
  "g\">12</property><child><object class=\"GtkBox\" id=\"vbox18\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"orientation\">vertical</property><property nam"
  "e=\"border_width\">6</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkRadioButton\" id=\"placement_center_option\"><"
  "property name=\"label\" translatable=\"yes\">At the c_enter of the scre"
  "en</property><property name=\"use_action_appearance\">False</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"use_underline\">True</property><property name=\"draw_indica"
  "tor\">True</property></object><packing><property name=\"expand\">True</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">0</property></packing></child><child><object class=\"GtkRadioButto"
  "n\" id=\"placement_mouse_option\"><property name=\"label\" translatable"
  "=\"yes\">U_nder the mouse pointer</property><property name=\"use_action"
  "_appearance\">False</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">False</property><property name=\"use_underline\">True</proper"
  "ty><property name=\"active\">True</property><property name=\"draw_indic"
  "ator\">True</property><property name=\"group\">placement_center_option<"
  "/property></object><packing><property name=\"expand\">True</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child></object></child></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">2</property></packing></child>"
  "</object><packing><property name=\"position\">4</property></packing></c"
  "hild><child type=\"tab\"><object class=\"GtkLabel\" id=\"label5\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">_Placement</pr"
  "operty><property name=\"use_underline\">True</property></object><packin"
  "g><property name=\"position\">4</property><property name=\"tab_fill\">F"
  "alse</property></packing></child><child><object class=\"GtkBox\" id=\"v"
  "box7\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"orientation\">vertical</propert"
  "y><property name=\"border_width\">12</property><property name=\"spacing"
  "\">6</property><child><object class=\"GtkCheckButton\" id=\"use_composi"
  "ting_check\"><property name=\"label\" translatable=\"yes\">_Enable disp"
  "lay compositing</property><property name=\"use_action_appearance\">Fals"
  "e</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkScrolledWindow\" id=\"use_compositing_box\"><property name=\"visib"
  "le\">True</property><property name=\"sensitive\">False</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"hscrollbar_polic"
  "y\">never</property><property name=\"vscrollbar_policy\">automatic</pro"
  "perty><child><object class=\"GtkViewport\" id=\"viewport1\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"resize_mode\">queue</property><property name=\"sh"
  "adow_type\">none</property><child><object class=\"GtkAlignment\" id=\"a"
  "lignment3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"bottom_padding\">6</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkBox\" id=\"vbox8\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ve"
  "rtical</property><property name=\"spacing\">6</property><child><object "
  "class=\"GtkCheckButton\" id=\"unredirect_overlays_check\"><property nam"
  "e=\"label\" translatable=\"yes\">Display _fullscreen overlay windows di"
  "rectly</property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">False</property><"
  "property name=\"use_underline\">True</property><property name=\"draw_in"
  "dicator\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkCheck"
  "Button\" id=\"cycle_preview_check\"><property name=\"label\" translatab"
  "le=\"yes\">Show windows preview in place of icons when cycling</propert"
  "y><property name=\"use_action_appearance\">False</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">2</pro"
  "perty></packing></child><child><object class=\"GtkCheckButton\" id=\"sh"
  "ow_popup_shadow_check\"><property name=\"label\" translatable=\"yes\">S"
  "how shadows under pop_up windows</property><property name=\"use_action_"
  "appearance\">False</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"use_underline\">True</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">3</property></packing></child><chil"
  "d><object class=\"GtkCheckButton\" id=\"show_dock_shadow_check\"><prope"
  "rty name=\"label\" translatable=\"yes\">Show shadows under _dock window"
  "s</property><property name=\"use_action_appearance\">False</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"draw_indicat"
  "or\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">4</property></packing></child><child><object class=\"GtkCheckButto"
  "n\" id=\"show_frame_shadow_check\"><property name=\"label\" translatabl"
  "e=\"yes\">Show shadows under _regular windows</property><property name="
  "\"use_action_appearance\">False</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_underline\">"
  "True</property><property name=\"draw_indicator\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">5</property></packing>"
  "</child><child><object class=\"GtkCheckButton\" id=\"zoom_desktop_check"
  "\"><property name=\"label\" translatable=\"yes\">Zoom desktop with mous"
  "e wheel</property><property name=\"use_action_appearance\">False</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">False</property>"
  "<property name=\"use_underline\">True</property><property name=\"draw_i"
  "ndicator\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "position\">6</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"zoom_pointer_check\"><property name=\"label\" translatab"
  "le=\"yes\">Zoom pointer along with the desktop</property><property name"
  "=\"use_action_appearance\">False</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">False</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">7</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"label12\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"xalign\">0</property><property name=\"label\" trans"
  "latable=\"yes\">Opaci_ty of window decorations:</property><property nam"
  "e=\"use_underline\">True</property><property name=\"mnemonic_widget\">f"
  "rame_opacity_scale</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">8</property></packing></child><child><object class=\"GtkAl"
  "ignment\" id=\"alignment5\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"top_paddin"
  "g\">2</property><property name=\"left_padding\">12</property><child><ob"
  "ject class=\"GtkBox\" id=\"hbox3\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"ori"
  "entation\">horizontal</property><child><object class=\"GtkLabel\" id=\""
  "label17\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">&lt;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkScale\" id=\"f"
  "rame_opacity_scale\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"orientation\">hori"
  "zontal</property><property name=\"adjustment\">adjustment2</property><p"
  "roperty name=\"restrict_to_fill_level\">False</property><property name="
  "\"draw_value\">False</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child><child><object class=\"Gtk"
  "Label\" id=\"label18\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_"
  "markup\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">2</property></packing></child></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">9</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label13\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"xalign\">0</property><property name=\"label\" translatable"
  "=\"yes\">Opacity of _inactive windows:</property><property name=\"use_u"
  "nderline\">True</property><property name=\"mnemonic_widget\">inactive_o"
  "pacity_scale</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">10</property></packing></child><child><object class=\"GtkAlign"
  "ment\" id=\"alignment6\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"top_padding\""
  ">2</property><property name=\"left_padding\">12</property><child><objec"
  "t class=\"GtkBox\" id=\"hbox4\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"orient"
  "ation\">horizontal</property><child><object class=\"GtkLabel\" id=\"lab"
  "el19\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">&l"
  "t;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkScale\" id=\"ina"
  "ctive_opacity_scale\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"orientation\">hor"
  "izontal</property><property name=\"adjustment\">adjustment3</property><"
  "property name=\"restrict_to_fill_level\">False</property><property name"
  "=\"draw_value\">False</property></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">1</property></packing></child><child><object class=\"Gt"
  "kLabel\" id=\"label20\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use"
  "_markup\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">False</property><property name=\""
  "position\">2</property></packing></child></object></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">11</property></packing></ch"
  "ild><child><object class=\"GtkLabel\" id=\"label14\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"xalign\">0</property><property name=\"label\" translatab"
  "le=\"yes\">Opacity of windows during _move:</property><property name=\""
  "use_underline\">True</property><property name=\"mnemonic_widget\">move_"
  "opacity_scale</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">12</property></packing></child><child><object class=\"GtkAlig"
  "nment\" id=\"alignment7\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"top_padding\""
  ">2</property><property name=\"left_padding\">12</property><child><objec"
  "t class=\"GtkBox\" id=\"hbox5\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"orient"
  "ation\">horizontal</property><child><object class=\"GtkLabel\" id=\"lab"
  "el21\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">&l"
  "t;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkScale\" id=\"mov"
  "e_opacity_scale\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">True</property><property name=\"orientation\">horizon"
  "tal</property><property name=\"adjustment\">adjustment4</property><prop"
  "erty name=\"restrict_to_fill_level\">False</property><property name=\"d"
  "raw_value\">False</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label22\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_mark"
  "up\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">2</property></packing></child></object></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">13</property></packing></child><"
  "child><object class=\"GtkLabel\" id=\"label15\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">Opacity of windows during resi_ze:</property><property name=\"use"
  "_underline\">True</property><property name=\"mnemonic_widget\">resize_o"
  "pacity_scale</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">14</property></packing></child><child><object class=\"GtkAlign"
  "ment\" id=\"alignment8\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"top_padding\""
  ">2</property><property name=\"left_padding\">12</property><child><objec"
  "t class=\"GtkBox\" id=\"hbox6\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"orient"
  "ation\">horizontal</property><child><object class=\"GtkLabel\" id=\"lab"
  "el23\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">&l"
  "t;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkScale\" id=\"res"
  "ize_opacity_scale\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"orientation\">horiz"
  "ontal</property><property name=\"adjustment\">adjustment5</property><pr"
  "operty name=\"restrict_to_fill_level\">False</property><property name=\""
  "draw_value\">False</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label24\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_mark"
  "up\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">2</property></packing></child></object></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">15</property></packing></child><"
  "child><object class=\"GtkLabel\" id=\"label16\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">Opacity of popup wi_ndows:</property><property name=\"use_underli"
  "ne\">True</property><property name=\"mnemonic_widget\">popup_opacity_sc"
  "ale</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "16</property></packing></child><child><object class=\"GtkAlignment\" id"
  "=\"alignment9\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"top_padding\">2</prope"
  "rty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkBox\" id=\"hbox7\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ho"
  "rizontal</property><child><object class=\"GtkLabel\" id=\"label25\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"label\" translatable=\"yes\">&lt;i&gt;Tra"
  "nsparent&lt;/i&gt;</property><property name=\"use_markup\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkScale\" id=\"popup_opacity"
  "_scale\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"orientation\">horizontal</prop"
  "erty><property name=\"adjustment\">adjustment6</property><property name"
  "=\"restrict_to_fill_level\">False</property><property name=\"draw_value"
  "\">False</property></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">1</property></packing></child><child><object class=\"GtkLabel\" id=\""
  "label26\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_markup\">True"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">2</"
  "property></packing></child></object></child></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">17</property></packing></child></object><"
  "/child></object></child></object></child></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"position\">5</property></packing></child><child type"
  "=\"tab\"><object class=\"GtkLabel\" id=\"label6\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">C_ompositor</property><propert"
  "y name=\"use_underline\">True</property></object><packing><property nam"
  "e=\"position\">5</property><property name=\"tab_fill\">False</property>"
  "</packing></child></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object></child><action-widgets><action"
  "-widget response=\"-11\">button2</action-widget><action-widget response"
  "=\"0\">button1</action-widget></action-widgets></object></interface>"
};

static const unsigned tweaks_dialog_ui_length = 48292u;

