/* automatically generated from xfwm4-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfwm4_dialog_ui)
#endif
#ifdef __GNUC__
static const char xfwm4_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfwm4_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkAdjustment\" id=\"adjustment1"
  "\"><property name=\"lower\">5</property><property name=\"upper\">2000</"
  "property><property name=\"value\">5</property><property name=\"step_inc"
  "rement\">1</property><property name=\"page_increment\">10</property></o"
  "bject><object class=\"GtkAdjustment\" id=\"adjustment2\"><property name"
  "=\"lower\">5</property><property name=\"upper\">2000</property><propert"
  "y name=\"value\">5</property><property name=\"step_increment\">1</prope"
  "rty><property name=\"page_increment\">10</property></object><object cla"
  "ss=\"GtkAdjustment\" id=\"adjustment3\"><property name=\"lower\">5</pro"
  "perty><property name=\"upper\">100</property><property name=\"value\">2"
  "0</property><property name=\"step_increment\">1</property><property nam"
  "e=\"page_increment\">10</property></object><object class=\"GtkAdjustmen"
  "t\" id=\"adjustment4\"><property name=\"lower\">5</property><property n"
  "ame=\"upper\">100</property><property name=\"value\">20</property><prop"
  "erty name=\"step_increment\">1</property><property name=\"page_incremen"
  "t\">10</property></object><object class=\"GtkImage\" id=\"image7\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"icon_name\">window-close</property></objec"
  "t><object class=\"GtkImage\" id=\"image8\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"icon_name\">help-browser</property></object><object class=\"XfceTi"
  "tledDialog\" id=\"main-dialog\"><property name=\"can_focus\">False</pro"
  "perty><property name=\"title\" translatable=\"yes\">Window Manager</pro"
  "perty><property name=\"window_position\">center-on-parent</property><pr"
  "operty name=\"icon_name\">org.xfce.xfwm4</property><property name=\"typ"
  "e_hint\">dialog</property><property name=\"subtitle\" translatable=\"ye"
  "s\">Configure window behavior and shortcuts</property><child internal-c"
  "hild=\"vbox\"><object class=\"GtkBox\" id=\"main-vbox\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"orientation\">vertical</property><child internal-chil"
  "d=\"action_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_are"
  "a1\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"layout_style\">end</property><chi"
  "ld><object class=\"GtkButton\" id=\"help_button\"><property name=\"labe"
  "l\" translatable=\"yes\">_Help</property><property name=\"use_action_ap"
  "pearance\">False</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">True</property><property name=\"image\">image8</property><proper"
  "ty name=\"use_underline\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">0</property><property name=\"secondary\">Tru"
  "e</property></packing></child><child><object class=\"GtkButton\" id=\"c"
  "lose_button\"><property name=\"label\" translatable=\"yes\">_Close</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">True</property><property nam"
  "e=\"image\">image7</property><property name=\"use_underline\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">1</prope"
  "rty></packing></child></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">True</property><property name=\"pack"
  "_type\">end</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkNotebook\" id=\"plug-child\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"border_width\">6</property><child><object clas"
  "s=\"GtkBox\" id=\"hbox7\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"orientation\""
  ">horizontal</property><property name=\"border_width\">12</property><pro"
  "perty name=\"spacing\">12</property><child><object class=\"GtkFrame\" i"
  "d=\"frame13\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label_xalign\">0</proper"
  "ty><property name=\"shadow_type\">none</property><child><object class=\""
  "GtkAlignment\" id=\"alignment11\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"top_"
  "padding\">6</property><property name=\"left_padding\">12</property><chi"
  "ld><object class=\"GtkScrolledWindow\" id=\"scrolledwindow3\"><property"
  " name=\"width_request\">200</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"h"
  "scrollbar_policy\">automatic</property><property name=\"vscrollbar_poli"
  "cy\">automatic</property><property name=\"shadow_type\">in</property><c"
  "hild><object class=\"GtkTreeView\" id=\"theme_name_treeview\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"headers_visible\">False</property></object></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label32\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"label\" "
  "translatable=\"yes\">&lt;b&gt;The_me&lt;/b&gt;</property><property name"
  "=\"use_markup\">True</property><property name=\"use_underline\">True</p"
  "roperty></object></child></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkBox\" "
  "id=\"vbox12\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"orientation\">vertical</"
  "property><property name=\"spacing\">6</property><child><object class=\""
  "GtkFrame\" id=\"frame10\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label_xalign"
  "\">0</property><property name=\"shadow_type\">none</property><child><ob"
  "ject class=\"GtkAlignment\" id=\"alignment14\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">6</property><property name=\"bottom_padding\">6"
  "</property><property name=\"left_padding\">12</property><child><object "
  "class=\"GtkFontButton\" id=\"title_font_button\"><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">True</property></object></child></object></child><child "
  "type=\"label\"><object class=\"GtkLabel\" id=\"label23\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label\" translatable=\"yes\">&lt;b&gt;Title fon_t&lt"
  ";/b&gt;</property><property name=\"use_markup\">True</property><propert"
  "y name=\"use_underline\">True</property><property name=\"mnemonic_widge"
  "t\">title_font_button</property></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><object class=\"GtkFrame\" id=\"frame11\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label_xalign\">0</property><property name=\"shadow_type\">none</pr"
  "operty><child><object class=\"GtkAlignment\" id=\"title_align_box\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"border_width\">6</property><property name"
  "=\"bottom_padding\">6</property><property name=\"left_padding\">12</pro"
  "perty><child><object class=\"GtkComboBox\" id=\"title_align_combo\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property></object></child></object></child><child type=\"label\"><o"
  "bject class=\"GtkLabel\" id=\"label24\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">&lt;b&gt;Title _alignment&lt;/b&gt;</pro"
  "perty><property name=\"use_markup\">True</property><property name=\"use"
  "_underline\">True</property><property name=\"mnemonic_widget\">title_al"
  "ign_combo</property></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">1</property></packing></child><child><object clas"
  "s=\"GtkFrame\" id=\"frame12\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"label_xa"
  "lign\">0</property><property name=\"shadow_type\">none</property><child"
  "><object class=\"GtkAlignment\" id=\"button_layout_box\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"bottom_padding\">6</property><property name=\"left_p"
  "adding\">12</property><child><object class=\"GtkBox\" id=\"vbox13\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"orientation\">vertical</property><propert"
  "y name=\"border_width\">6</property><property name=\"spacing\">6</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label26\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"xalign\">0</property><property name=\"label\" translatab"
  "le=\"yes\">Click and drag the buttons to change the layout</property></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">0</property></pack"
  "ing></child><child><object class=\"GtkFrame\" id=\"active-frame\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label_xalign\">0</property><child><object c"
  "lass=\"GtkAlignment\" id=\"alignment17\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"border_width\">6</property><child><object class=\"GtkBox\" id=\"acti"
  "ve-box\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"orientation\">horizontal</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "Button\" id=\"button-layout-|\"><property name=\"label\" translatable=\""
  "yes\">Title</property><property name=\"use_action_appearance\">False</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">True</proper"
  "ty><property name=\"tooltip_text\" translatable=\"yes\">The window titl"
  "e cannot be removed</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">0</property></packing></child></object></child></object"
  "></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label27\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Active</"
  "property><property name=\"use_markup\">True</property></object></child>"
  "</object><packing><property name=\"expand\">True</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child><child><object class=\"GtkFrame\" id=\"hidden-frame\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"label_xalign\">0</property><child><object"
  " class=\"GtkAlignment\" id=\"alignment18\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"border_width\">6</property><child><object class=\"GtkBox\" id=\"hi"
  "dden-box\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"orientation\">horizontal</p"
  "roperty><property name=\"spacing\">6</property><child><object class=\"G"
  "tkButton\" id=\"button-layout-O\"><property name=\"use_action_appearanc"
  "e\">False</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "True</property><property name=\"tooltip_text\" translatable=\"yes\">Men"
  "u</property><child><object class=\"GtkImage\" id=\"image1\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"icon_name\">xfce-wm-menu</property></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkButton\" id=\"button-layou"
  "t-T\"><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">True</property><property nam"
  "e=\"tooltip_text\" translatable=\"yes\">Stick</property><child><object "
  "class=\"GtkImage\" id=\"image2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"icon_"
  "name\">xfce-wm-stick</property></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">1</property></packing></child><child>"
  "<object class=\"GtkButton\" id=\"button-layout-S\"><property name=\"use"
  "_action_appearance\">False</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">Shade</property><child><object class=\"GtkImage\" id=\"im"
  "age3\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"icon_name\">xfce-wm-shade</prop"
  "erty></object></child></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">False</property><property name=\"pos"
  "ition\">2</property></packing></child><child><object class=\"GtkButton\""
  " id=\"button-layout-H\"><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">True</prop"
  "erty><property name=\"tooltip_text\" translatable=\"yes\">Minimize</pro"
  "perty><child><object class=\"GtkImage\" id=\"image4\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"icon_name\">xfce-wm-minimize</property></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">False</property><property name=\"position\">3</property><"
  "/packing></child><child><object class=\"GtkButton\" id=\"button-layout-"
  "M\"><property name=\"use_action_appearance\">False</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><property name="
  "\"tooltip_text\" translatable=\"yes\">Maximize</property><child><object"
  " class=\"GtkImage\" id=\"image5\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"icon"
  "_name\">xfce-wm-maximize</property></object></child></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">False<"
  "/property><property name=\"position\">4</property></packing></child><ch"
  "ild><object class=\"GtkButton\" id=\"button-layout-C\"><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"tooltip_text\" trans"
  "latable=\"yes\">Close</property><child><object class=\"GtkImage\" id=\""
  "image6\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"icon_name\">xfce-wm-close</pr"
  "operty></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">5</property></packing></child></object></child></object></chi"
  "ld><child type=\"label\"><object class=\"GtkLabel\" id=\"label28\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">Hidden</prope"
  "rty><property name=\"use_markup\">True</property></object></child></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label25\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">&lt;b&gt;Button layout&lt;/b&gt;</property><"
  "property name=\"use_markup\">True</property></object></child></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">2</property></packing></"
  "child></object><packing><property name=\"expand\">True</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">1</propert"
  "y></packing></child></object></child><child type=\"tab\"><object class="
  "\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">_Style</property><property name=\"use_underline\">Tru"
  "e</property></object><packing><property name=\"tab_fill\">False</proper"
  "ty></packing></child><child><object class=\"GtkBox\" id=\"vbox10\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"orientation\">vertical</property><property"
  " name=\"border_width\">12</property><property name=\"spacing\">6</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label22\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"xalign\">0</property><property name=\"label\" translatab"
  "le=\"yes\">Define shortcuts to perform _window manager actions:</proper"
  "ty><property name=\"use_markup\">True</property><property name=\"use_un"
  "derline\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">False</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkBox\""
  " id=\"vbox11\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"orientation\">vertical<"
  "/property><property name=\"spacing\">6</property><child><object class=\""
  "GtkScrolledWindow\" id=\"scrolledwindow2\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"hscrollbar_policy\">never</property><property name=\"vscrollbar_pol"
  "icy\">automatic</property><property name=\"shadow_type\">in</property><"
  "child><object class=\"GtkTreeView\" id=\"shortcuts_treeview\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty></object></child></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">0</property></packing></child><child><placeholder/></child></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child><child><object class=\"GtkAlignment\" id=\"alignment15\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"yalign\">0</property><property name=\"xscal"
  "e\">0</property><child><object class=\"GtkBox\" id=\"hbox5\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"orientation\">horizontal</property><property nam"
  "e=\"spacing\">6</property><child><object class=\"GtkButton\" id=\"short"
  "cuts_edit_button\"><property name=\"label\">gtk-edit</property><propert"
  "y name=\"use_action_appearance\">False</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">True</property><property name=\"use_stock\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkButton\" id=\""
  "shortcuts_clear_button\"><property name=\"label\">gtk-clear</property><"
  "property name=\"use_action_appearance\">False</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">True</property><property name=\"use"
  "_stock\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">1</property></packing></child><child><object class=\"GtkButto"
  "n\" id=\"shortcuts_reset_button\"><property name=\"label\" translatable"
  "=\"yes\">_Reset to Defaults</property><property name=\"use_action_appea"
  "rance\">False</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">True</property><property name=\"use_underline\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"padding\">15</property><prope"
  "rty name=\"pack_type\">end</property><property name=\"position\">2</pro"
  "perty></packing></child></object></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">2</property></packing></child></object><pack"
  "ing><property name=\"position\">1</property></packing></child><child ty"
  "pe=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">_Keyboard</property><propert"
  "y name=\"use_underline\">True</property></object><packing><property nam"
  "e=\"position\">1</property><property name=\"tab_fill\">False</property>"
  "</packing></child><child><object class=\"GtkBox\" id=\"vbox7\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"orientation\">vertical</property><property nam"
  "e=\"border_width\">12</property><property name=\"spacing\">6</property>"
  "<child><object class=\"GtkFrame\" id=\"frame5\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"label_xalign\">0</property><property name=\"shadow_type\">non"
  "e</property><child><object class=\"GtkAlignment\" id=\"alignment7\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"border_width\">6</property><property name"
  "=\"bottom_padding\">6</property><property name=\"left_padding\">12</pro"
  "perty><child><object class=\"GtkBox\" id=\"vbox14\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"orientation\">vertical</property><property name=\"spacing"
  "\">6</property><child><object class=\"GtkBox\" id=\"hbox3\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"orientation\">horizontal</property><property name"
  "=\"spacing\">12</property><property name=\"homogeneous\">True</property"
  "><child><object class=\"GtkRadioButton\" id=\"click_to_focus_radio\"><p"
  "roperty name=\"label\" translatable=\"yes\">Click to foc_us</property><"
  "property name=\"use_action_appearance\">False</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"us"
  "e_underline\">True</property><property name=\"draw_indicator\">True</pr"
  "operty></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkRadioButton\" id=\"focus"
  "_follows_mouse_radio\"><property name=\"label\" translatable=\"yes\">Fo"
  "cus follows _mouse</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property><property name=\"group\">click_to_"
  "focus_radio</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkLabel\" id=\"label29\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"xalign\">0"
  "</property><property name=\"label\" translatable=\"yes\">_Delay before "
  "window receives focus:</property><property name=\"use_markup\">True</pr"
  "operty><property name=\"use_underline\">True</property><property name=\""
  "mnemonic_widget\">focus_delay_scale</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child><child><obj"
  "ect class=\"GtkAlignment\" id=\"alignment19\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\""
  "focus_delay_hbox\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"orientation\">horiz"
  "ontal</property><property name=\"spacing\">12</property><child><object "
  "class=\"GtkLabel\" id=\"label30\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\" comments=\"Focus delay\">&lt;i&gt;Short&lt;/i&"
  "gt;</property><property name=\"use_markup\">True</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkScale\" id=\"focus_delay_scale\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"orientation\">horizontal</property><property na"
  "me=\"adjustment\">adjustment1</property><property name=\"draw_value\">F"
  "alse</property></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">1"
  "</property></packing></child><child><object class=\"GtkLabel\" id=\"lab"
  "el31\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\" co"
  "mments=\"Focus delay\">&lt;i&gt;Long&lt;/i&gt;</property><property name"
  "=\"use_markup\">True</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">False</property><property n"
  "ame=\"position\">2</property></packing></child></object></child></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">2</property></packing><"
  "/child></object></child></object></child><child type=\"label\"><object "
  "class=\"GtkLabel\" id=\"label15\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">&lt;b&gt;Focus model&lt;/b&gt;</property><prop"
  "erty name=\"use_markup\">True</property></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkFrame\" id=\"frame6\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label_xalign\">0</property><property name=\"shadow_type\">n"
  "one</property><child><object class=\"GtkAlignment\" id=\"alignment8\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"border_width\">6</property><property na"
  "me=\"bottom_padding\">6</property><property name=\"left_padding\">12</p"
  "roperty><child><object class=\"GtkCheckButton\" id=\"focus_new_check\">"
  "<property name=\"label\" translatable=\"yes\">Automatically give focus "
  "to _newly created windows</property><property name=\"use_action_appeara"
  "nce\">False</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object></child></object></"
  "child><child type=\"label\"><object class=\"GtkLabel\" id=\"label16\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;N"
  "ew window focus&lt;/b&gt;</property><property name=\"use_markup\">True<"
  "/property></object></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">1</property></packing></child><child><object class=\"GtkFr"
  "ame\" id=\"frame7\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label_xalign\">0</"
  "property><property name=\"shadow_type\">none</property><child><object c"
  "lass=\"GtkAlignment\" id=\"alignment9\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"border_width\">6</property><property name=\"bottom_padding\">6</prope"
  "rty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkBox\" id=\"vbox8\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ve"
  "rtical</property><property name=\"spacing\">6</property><child><object "
  "class=\"GtkCheckButton\" id=\"raise_on_focus_check\"><property name=\"l"
  "abel\" translatable=\"yes\">Automatically _raise windows when they rece"
  "ive focus</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"use_underline\">True</property><property name=\"draw"
  "_indicator\">True</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkBox\""
  " id=\"vbox9\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"orientation\">vertical</"
  "property><property name=\"spacing\">6</property><child><object class=\""
  "GtkLabel\" id=\"label19\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"xalign\">0</"
  "property><property name=\"label\" translatable=\"yes\">Delay _before ra"
  "ising focused window:</property><property name=\"use_underline\">True</"
  "property><property name=\"mnemonic_widget\">focus_raise_delay_scale</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkAlignment\" id=\"align"
  "ment1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"left_padding\">12</property><c"
  "hild><object class=\"GtkBox\" id=\"hbox4\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"orientation\">horizontal</property><property name=\"spacing\">12</"
  "property><child><object class=\"GtkLabel\" id=\"label20\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label\" translatable=\"yes\" comments=\"Raise focus"
  " delay\">&lt;i&gt;Short&lt;/i&gt;</property><property name=\"use_markup"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkScale\" id="
  "\"focus_raise_delay_scale\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"orientation"
  "\">horizontal</property><property name=\"adjustment\">adjustment2</prop"
  "erty><property name=\"draw_value\">False</property></object><packing><p"
  "roperty name=\"expand\">True</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">1</property></packing></child><child"
  "><object class=\"GtkLabel\" id=\"label21\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\" comments=\"Raise focus delay\">&lt;i&"
  "gt;Long&lt;/i&gt;</property><property name=\"use_markup\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">2</property>"
  "</packing></child></object></child></object><packing><property name=\"e"
  "xpand\">True</property><property name=\"fill\">True</property><property"
  " name=\"position\">1</property></packing></child></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "></child></object></child><child type=\"label\"><object class=\"GtkLabe"
  "l\" id=\"label17\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">&lt;b&gt;Raise on focus&lt;/b&gt;</property><property name=\""
  "use_markup\">True</property></object></child></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">2</property></packing></child><child><ob"
  "ject class=\"GtkFrame\" id=\"frame8\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment10\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"border_width\">6</property><property name=\"bottom"
  "_padding\">6</property><property name=\"left_padding\">12</property><ch"
  "ild><object class=\"GtkCheckButton\" id=\"raise_on_click_check\"><prope"
  "rty name=\"label\" translatable=\"yes\">Raise window when clicking _ins"
  "ide application window</property><property name=\"use_action_appearance"
  "\">False</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object></child></object></ch"
  "ild><child type=\"label\"><object class=\"GtkLabel\" id=\"label18\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Rai"
  "se on click&lt;/b&gt;</property><property name=\"use_markup\">True</pro"
  "perty></object></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">3</property></packing></child></object><packing><property name"
  "=\"position\">2</property></packing></child><child type=\"tab\"><object"
  " class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">_Focus</property><property name=\"use_underlin"
  "e\">True</property></object><packing><property name=\"position\">2</pro"
  "perty><property name=\"tab_fill\">False</property></packing></child><ch"
  "ild><object class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"orientation\">vertical</property><property name=\"border_width\">12"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label_xalig"
  "n\">0</property><property name=\"shadow_type\">none</property><child><o"
  "bject class=\"GtkAlignment\" id=\"alignment2\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">6</property><property name=\"bottom_padding\">6"
  "</property><property name=\"left_padding\">12</property><child><object "
  "class=\"GtkBox\" id=\"vbox2\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"orientat"
  "ion\">vertical</property><property name=\"spacing\">6</property><child>"
  "<object class=\"GtkBox\" id=\"hbox8\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "orientation\">horizontal</property><child><object class=\"GtkCheckButto"
  "n\" id=\"snap_to_border_check\"><property name=\"label\" translatable=\""
  "yes\">To screen _borders</property><property name=\"use_action_appearan"
  "ce\">False</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkCheckButton\" id=\"snap_to_window_check\"><property name=\""
  "label\" translatable=\"yes\">To other _windows</property><property name"
  "=\"use_action_appearance\">False</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">False</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">True</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkBox\" id=\"vbox5\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"orientation\">vertical</property><property"
  " name=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"la"
  "bel9\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"xalign\">0</property><property "
  "name=\"label\" translatable=\"yes\">Dis_tance:</property><property name"
  "=\"use_underline\">True</property><property name=\"mnemonic_widget\">sn"
  "ap_width_scale</property></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment6\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkBox\" id=\"hbox1\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"orientation\">horizontal</property><property name="
  "\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"label11"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label\" translatable=\"yes\" commen"
  "ts=\"Snapping distance\">&lt;i&gt;Small&lt;/i&gt;</property><property n"
  "ame=\"use_markup\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkScale\" id=\"snap_width_scale\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"or"
  "ientation\">horizontal</property><property name=\"adjustment\">adjustme"
  "nt3</property><property name=\"restrict_to_fill_level\">False</property"
  "><property name=\"draw_value\">False</property></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">1</property></packing></child><child><ob"
  "ject class=\"GtkLabel\" id=\"label12\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\" comments=\"Snapping distance\">&lt;i&gt;Wi"
  "de&lt;/i&gt;</property><property name=\"use_markup\">True</property></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">False</property><property name=\"position\">2</property></pac"
  "king></child></object></child></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">1</property></packing></child></object><packing><property"
  " name=\"expand\">True</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child></object></ch"
  "ild></object></child><child type=\"label\"><object class=\"GtkLabel\" i"
  "d=\"label5\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">&lt;b&gt;Windows snapping&lt;/b&gt;</property><property name=\"use_m"
  "arkup\">True</property></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkFrame\" id=\"frame2\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label_"
  "xalign\">0</property><property name=\"shadow_type\">none</property><chi"
  "ld><object class=\"GtkAlignment\" id=\"alignment3\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"border_width\">6</property><property name=\"bottom_paddin"
  "g\">6</property><property name=\"left_padding\">12</property><child><ob"
  "ject class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"ori"
  "entation\">vertical</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkBox\" id=\"hbox9\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"orientation\">horizontal</property><child><object class=\"GtkCheck"
  "Button\" id=\"wrap_workspaces_check\"><property name=\"label\" translat"
  "able=\"yes\">With the mouse _pointer</property><property name=\"use_act"
  "ion_appearance\">False</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">False</property><property name=\"use_underline\">True</pro"
  "perty><property name=\"draw_indicator\">True</property></object><packin"
  "g><property name=\"expand\">True</property><property name=\"fill\">True"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkCheckButton\" id=\"wrap_windows_check\"><proper"
  "ty name=\"label\" translatable=\"yes\">With a _dragged window</property"
  "><property name=\"use_action_appearance\">False</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">1</prop"
  "erty></packing></child></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">0</property></packing></child><child><object class=\"GtkBox\" id"
  "=\"vbox6\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "Label\" id=\"label10\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"xalign\">0</pro"
  "perty><property name=\"label\" translatable=\"yes\">_Edge resistance:</"
  "property><property name=\"use_underline\">True</property><property name"
  "=\"selectable\">True</property><property name=\"mnemonic_widget\">wrap_"
  "resistance_scale</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkAl"
  "ignment\" id=\"alignment4\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"left_paddi"
  "ng\">12</property><child><object class=\"GtkBox\" id=\"hbox2\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"orientation\">horizontal</property><property n"
  "ame=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"lab"
  "el13\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\" co"
  "mments=\"Edge resistance\">&lt;i&gt;Small&lt;/i&gt;</property><property"
  " name=\"use_markup\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkScale\" id=\"wrap_resistance_scale\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"orientation\">horizontal</property><property name=\"adjustment\">a"
  "djustment4</property><property name=\"restrict_to_fill_level\">False</p"
  "roperty><property name=\"draw_value\">False</property></object><packing"
  "><property name=\"expand\">True</property><property name=\"fill\">True<"
  "/property><property name=\"position\">1</property></packing></child><ch"
  "ild><object class=\"GtkLabel\" id=\"label14\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\" comments=\"Edge resistance\">&lt;i&"
  "gt;Wide&lt;/i&gt;</property><property name=\"use_markup\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">2</property>"
  "</packing></child></object></child></object><packing><property name=\"e"
  "xpand\">True</property><property name=\"fill\">True</property><property"
  " name=\"position\">1</property></packing></child></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "></child></object></child><child type=\"label\"><object class=\"GtkLabe"
  "l\" id=\"label6\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label\" translatable"
  "=\"yes\">&lt;b&gt;Wrap workspaces when reaching the screen edge&lt;/b&g"
  "t;</property><property name=\"use_markup\">True</property></object></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child><child><object class=\"GtkFrame\" id=\"frame3\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label_xalign\">0</property><property name="
  "\"shadow_type\">none</property><child><object class=\"GtkAlignment\" id"
  "=\"alignment5\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"border_width\">6</prop"
  "erty><property name=\"bottom_padding\">6</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkBox\" id=\"hbox6\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"orientation\">horizontal</property><chi"
  "ld><object class=\"GtkCheckButton\" id=\"box_move_check\"><property nam"
  "e=\"label\" translatable=\"yes\">When _moving</property><property name="
  "\"use_action_appearance\">False</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_underline\">"
  "True</property><property name=\"draw_indicator\">True</property></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkCheckButton\" id=\"box_resize_check\">"
  "<property name=\"label\" translatable=\"yes\">When _resizing</property>"
  "<property name=\"use_action_appearance\">False</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"receives_default\">False</property><property name=\"u"
  "se_underline\">True</property><property name=\"draw_indicator\">True</p"
  "roperty></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">1</prope"
  "rty></packing></child></object></child></object></child><child type=\"l"
  "abel\"><object class=\"GtkLabel\" id=\"label7\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"label\" translatable=\"yes\">&lt;b&gt;Hide content of windows"
  "&lt;/b&gt;</property><property name=\"use_markup\">True</property></obj"
  "ect></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">2</"
  "property></packing></child><child><object class=\"GtkFrame\" id=\"frame"
  "4\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment13\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"top_padding\""
  ">6</property><property name=\"bottom_padding\">6</property><property na"
  "me=\"left_padding\">18</property><child><object class=\"GtkComboBox\" i"
  "d=\"double_click_action_combo\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"toolti"
  "p_text\" translatable=\"yes\">The action to perform when the title-bar "
  "is double-clicked</property></object></child></object></child><child ty"
  "pe=\"label\"><object class=\"GtkLabel\" id=\"label8\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">&lt;b&gt;Double click _act"
  "ion&lt;/b&gt;</property><property name=\"use_markup\">True</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"mnemonic"
  "_widget\">double_click_action_combo</property></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">3</property></packing><"
  "/child></object><packing><property name=\"position\">3</property></pack"
  "ing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label4\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Ad_vance"
  "d</property><property name=\"use_underline\">True</property></object><p"
  "acking><property name=\"position\">3</property><property name=\"tab_fil"
  "l\">False</property></packing></child></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">1</property></packing></child></object></child><a"
  "ction-widgets><action-widget response=\"-11\">help_button</action-widge"
  "t><action-widget response=\"0\">close_button</action-widget></action-wi"
  "dgets></object><object class=\"GtkSizeGroup\" id=\"sizegroup1\"><proper"
  "ty name=\"mode\">vertical</property><widgets><widget name=\"alignment17"
  "\"/><widget name=\"alignment18\"/></widgets></object></interface>"
};

static const unsigned xfwm4_dialog_ui_length = 49808u;

