/* automatically generated from xfwm4-workspace-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (workspace_dialog_ui)
#endif
#ifdef __GNUC__
static const char workspace_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char workspace_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkAdjustment\" id=\"adjustment1"
  "\"><property name=\"lower\">1</property><property name=\"upper\">100</p"
  "roperty><property name=\"step_increment\">1</property><property name=\""
  "page_increment\">10</property></object><object class=\"GtkAdjustment\" "
  "id=\"adjustment2\"><property name=\"upper\">100</property><property nam"
  "e=\"step_increment\">1</property><property name=\"page_increment\">10</"
  "property></object><object class=\"GtkAdjustment\" id=\"adjustment3\"><p"
  "roperty name=\"upper\">100</property><property name=\"step_increment\">"
  "1</property><property name=\"page_increment\">10</property></object><ob"
  "ject class=\"GtkAdjustment\" id=\"adjustment4\"><property name=\"upper\""
  ">100</property><property name=\"step_increment\">1</property><property "
  "name=\"page_increment\">10</property></object><object class=\"GtkAdjust"
  "ment\" id=\"adjustment5\"><property name=\"upper\">100</property><prope"
  "rty name=\"step_increment\">1</property><property name=\"page_increment"
  "\">10</property></object><object class=\"XfceTitledDialog\" id=\"main-d"
  "ialog\"><property name=\"can_focus\">False</property><property name=\"t"
  "itle\" translatable=\"yes\">Workspaces</property><property name=\"windo"
  "w_position\">center-on-parent</property><property name=\"icon_name\">or"
  "g.xfce.workspaces</property><property name=\"type_hint\">dialog</proper"
  "ty><property name=\"subtitle\" translatable=\"yes\">Configure layout, n"
  "ames and margins</property><child internal-child=\"vbox\"><object class"
  "=\"GtkBox\" id=\"main-vbox\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">2</property><child><"
  "object class=\"GtkNotebook\" id=\"plug-child\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"border_width\">6</property><child><object class=\"GtkBox\" id=\""
  "vbox1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"border_width\">6</property><property name=\"spacing"
  "\">6</property><child><object class=\"GtkFrame\" id=\"frame4\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label_xalign\">0</property><property name=\"sh"
  "adow_type\">none</property><child><object class=\"GtkAlignment\" id=\"a"
  "lignment4\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"top_padding\">6</property>"
  "<property name=\"bottom_padding\">6</property><property name=\"left_pad"
  "ding\">16</property><child><object class=\"GtkBox\" id=\"hbox3\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"orientation\">horizontal</property><property"
  " name=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"l"
  "abel3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"xalign\">0</property><property"
  " name=\"label\" translatable=\"yes\">_Number of workspaces:</property><"
  "property name=\"use_underline\">True</property><property name=\"mnemoni"
  "c_widget\">workspace_count_spinbutton</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkSpinButton\" id=\"workspace_count_spinbutton\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"editable\">True</property><property name=\"in"
  "visible_char\">\342\200\242</property><property name=\"primary_icon_act"
  "ivatable\">False</property><property name=\"secondary_icon_activatable\""
  ">False</property><property name=\"primary_icon_sensitive\">True</proper"
  "ty><property name=\"secondary_icon_sensitive\">True</property><property"
  " name=\"adjustment\">adjustment1</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">1</property></packing></child></object></c"
  "hild></object></child><child type=\"label\"><object class=\"GtkLabel\" "
  "id=\"label7\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">Layout</property><property name=\"use_markup\">True</property><att"
  "ributes><attribute name=\"weight\" value=\"bold\"/></attributes></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkFrame\" id=\"frame5\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><property "
  "name=\"shadow_type\">none</property><child><object class=\"GtkAlignment"
  "\" id=\"alignment5\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"top_padding\">6</"
  "property><property name=\"left_padding\">18</property><child><object cl"
  "ass=\"GtkScrolledWindow\" id=\"scrolledwindow1\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"hscrollbar_policy\">never</property><property name=\"vscrollb"
  "ar_policy\">automatic</property><property name=\"shadow_type\">etched-i"
  "n</property><child><object class=\"GtkTreeView\" id=\"treeview_ws_names"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"rules_hint\">True</property></object"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">Names</property><property name=\"use_markup\""
  ">True</property><attributes><attribute name=\"weight\" value=\"bold\"/>"
  "</attributes></object></child></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">1</property></packing></child></object></child><child typ"
  "e=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"label\" translatable=\"yes\">_General</property><property "
  "name=\"use_underline\">True</property></object><packing><property name="
  "\"tab_fill\">False</property></packing></child><child><object class=\"G"
  "tkBox\" id=\"vbox2\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"orientation\">ver"
  "tical</property><property name=\"border_width\">6</property><property n"
  "ame=\"spacing\">6</property><child><object class=\"GtkBox\" id=\"hbox1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"orientation\">horizontal</property><p"
  "roperty name=\"spacing\">12</property><child><object class=\"GtkImage\""
  " id=\"image1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"stock\">gtk-info</prope"
  "rty><property name=\"icon-size\">6</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"x"
  "align\">0</property><property name=\"label\" translatable=\"yes\">Margi"
  "ns are areas on the edges of the screen where no window will be placed<"
  "/property><property name=\"wrap\">True</property></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkAlignment\" id=\"alignment3\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"xscale\">0</property><property name=\"yscale\""
  ">0</property><child><object class=\"GtkTable\" id=\"table1\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"n_rows\">3</property><property name=\"n_columns\""
  ">3</property><property name=\"column_spacing\">6</property><property na"
  "me=\"row_spacing\">6</property><child><placeholder/></child><child><pla"
  "ceholder/></child><child><object class=\"GtkSpinButton\" id=\"margin_le"
  "ft_spinbutton\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"invisible_char\">\342\200"
  "\242</property><property name=\"primary_icon_activatable\">False</prope"
  "rty><property name=\"secondary_icon_activatable\">False</property><prop"
  "erty name=\"primary_icon_sensitive\">True</property><property name=\"se"
  "condary_icon_sensitive\">True</property><property name=\"adjustment\">a"
  "djustment2</property></object><packing><property name=\"top_attach\">1<"
  "/property><property name=\"bottom_attach\">2</property><property name=\""
  "x_options\"/><property name=\"y_options\"/></packing></child><child><ob"
  "ject class=\"GtkSpinButton\" id=\"margin_bottom_spinbutton\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"invisible_char\">\342\200\242</property><property"
  " name=\"primary_icon_activatable\">False</property><property name=\"sec"
  "ondary_icon_activatable\">False</property><property name=\"primary_icon"
  "_sensitive\">True</property><property name=\"secondary_icon_sensitive\""
  ">True</property><property name=\"adjustment\">adjustment3</property></o"
  "bject><packing><property name=\"left_attach\">1</property><property nam"
  "e=\"right_attach\">2</property><property name=\"top_attach\">2</propert"
  "y><property name=\"bottom_attach\">3</property><property name=\"x_optio"
  "ns\"/><property name=\"y_options\"/></packing></child><child><object cl"
  "ass=\"GtkSpinButton\" id=\"margin_right_spinbutton\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"invisible_char\">\342\200\242</property><property name=\""
  "primary_icon_activatable\">False</property><property name=\"secondary_i"
  "con_activatable\">False</property><property name=\"primary_icon_sensiti"
  "ve\">True</property><property name=\"secondary_icon_sensitive\">True</p"
  "roperty><property name=\"adjustment\">adjustment4</property></object><p"
  "acking><property name=\"left_attach\">2</property><property name=\"righ"
  "t_attach\">3</property><property name=\"top_attach\">1</property><prope"
  "rty name=\"bottom_attach\">2</property><property name=\"x_options\"/><p"
  "roperty name=\"y_options\"/></packing></child><child><placeholder/></ch"
  "ild><child><object class=\"GtkImage\" id=\"monitor_icon\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"xpad\">6</property><property name=\"ypad\">6</prope"
  "rty><property name=\"stock\">gtk-missing-image</property></object><pack"
  "ing><property name=\"left_attach\">1</property><property name=\"right_a"
  "ttach\">2</property><property name=\"top_attach\">1</property><property"
  " name=\"bottom_attach\">2</property></packing></child><child><object cl"
  "ass=\"GtkSpinButton\" id=\"margin_top_spinbutton\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"invisible_char\">\342\200\242</property><property name=\"pr"
  "imary_icon_activatable\">False</property><property name=\"secondary_ico"
  "n_activatable\">False</property><property name=\"primary_icon_sensitive"
  "\">True</property><property name=\"secondary_icon_sensitive\">True</pro"
  "perty><property name=\"adjustment\">adjustment5</property></object><pac"
  "king><property name=\"left_attach\">1</property><property name=\"right_"
  "attach\">2</property><property name=\"x_options\"/><property name=\"y_o"
  "ptions\"/></packing></child><child><placeholder/></child><child><placeh"
  "older/></child><child><placeholder/></child><child><placeholder/></chil"
  "d></object></child></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">1</property></packing></child></object><packing><property name=\"pos"
  "ition\">1</property></packing></child><child type=\"tab\"><object class"
  "=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"label\" tr"
  "anslatable=\"yes\">_Margins</property><property name=\"use_underline\">"
  "True</property></object><packing><property name=\"position\">1</propert"
  "y><property name=\"tab_fill\">False</property></packing></child></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child internal-child=\"action_area\"><object class=\"GtkButtonB"
  "ox\" id=\"dialog-action_area1\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"orient"
  "ation\">horizontal</property><property name=\"layout_style\">end</prope"
  "rty><child><object class=\"GtkButton\" id=\"button2\"><property name=\""
  "label\">gtk-help</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"use_stock\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">0</property><property name=\"secon"
  "dary\">True</property></packing></child><child><object class=\"GtkButto"
  "n\" id=\"button1\"><property name=\"label\">gtk-close</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"use_stock"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"pack_ty"
  "pe\">end</property><property name=\"position\">1</property></packing></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">True</property><property name=\"pack_type\">end</pro"
  "perty><property name=\"position\">0</property></packing></child></objec"
  "t></child><action-widgets><action-widget response=\"-11\">button2</acti"
  "on-widget><action-widget response=\"0\">button1</action-widget></action"
  "-widgets></object></interface>"
};

static const unsigned workspace_dialog_ui_length = 14016u;

